# Generated by Django 5.0 on 2024-01-04 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0003_category_image_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
