# Generated by Django 5.0 on 2024-02-29 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0005_rename_image_image_image_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='like_counts',
            field=models.IntegerField(default=0),
        ),
    ]
